app:
  domain: http://localhost:81

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/shortener_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect